#!/bin/sh

echo 'Updating footers'

for file in $(git diff --cached --name-only | grep -E '\.html$')
do
  sed -i'.bak' -r -E "s#(<aside>Last modified )(.*)(</aside>)#\1$(date +'%A, %B %e, %Y')\3#g" "$file"
  rm "$file.bak"
  git add $file
done

echo 'Optimizing PNGs'

for file in $(git diff --cached --name-only | grep -E '\.png$')
do
  if [[ -f "$file" ]]; then
    test $file && optipng $file
    git add $file
  fi
done
