#!/bin/sh

echo 'Updating footers'

for file in $(git diff --cached --name-only | grep -E '\.html$')
do
  sed -i'.bak' -r -E "s#(<aside>Last modified )(.*)(</aside>)#\1$(date +'%A, %B %e, %Y')\3#g" "$file"
  rm *.bak
  git add $file
done
